sudo: required

language: go

services:
  - docker

before_install:
  - docker build -t terraform .
  - docker run -d terraform export TERRAFORM_VERSION="$(terraform version)"
  - docker ps -a

script:
- echo $TERRAFORM_VERSION
