sudo: required

services:
  - docker

before_install:
  - docker build -t terraform .
  - docker run -d terraform bash -c "terraform version"
  - docker ps -a

script:
  - bundle exec rspec spec/specs.rb
